site_name: goInception使用文档
site_url: https://github.com/hanchuanchuan/goInception/
repo_url: https://github.com/hanchuanchuan/goInception/
repo_name: GitHub
site_description: goInception使用文档
site_author: hanchuanchuan
theme: readthedocs
dev_addr: 0.0.0.0:8000
# pages:
# - ['index.md', 'index']
# # - ['docs/QUICKSTART.md', '快速开始']
nav:
    # - 索引: index.md
    - 介绍: index.md
    - 安装: install.md
    - 调用选项: params.md
    - 使用示例: demo.md
    - config.toml说明: config.md
    - 审核选项: options.md
    - 审核规则: rules.md
    - 备份功能: backup.md
    - DDL变更:pt-osc: osc.md
    - DDL变更:gh-ost: ghost.md
    - KILL操作: kill_stmt.md
    - 自定义审核级别: levels.md
    - 统计功能: statistics.md
    - 语法树打印: tree.md
    - 赞助&定制: support.md
    - 更新日志: changelog.md
    # - About: about.md
